apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "face-detector.fullname" . }}
  labels:
    app: {{ include "face-detector.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "face-detector.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "face-detector.fullname" . }}
    spec:
      containers:
        - name: face-detector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.service.containerPort }}"
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.service.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: {{ toYaml .Values.resources | nindent 10 }}
