apiVersion: v1
kind: Service
metadata:
  name: {{ include "face-detector.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "face-detector.fullname" . }}-frontend